project:
  type: book
  output-dir: docs
  resources:
    - images

book:
  title: "STRAT 490R - Understanding AI: From Foundations to Strategy"
  favicon: images/understanding-ai-favicon.png
  author: "Scott Murff"
  date: "5/10/2025"
  chapters:
    - index.qmd
    - 00-math-review.qmd
    - 01-machine-learning.qmd
    - 02-deep-learning.qmd
    - 03-llms.qmd
    - 04-strategy.qmd
    - 90-resources.qmd
    - 98-faq.qmd
    - 99-references.qmd

bibliography: references.bib
csl: informs.csl

format:
  html:
    theme: cosmo
    link-external-icon: true
    link-external-newwindow: true
    css: styles.css
    markdown: default
    toc-title: On this page

number-sections: true
