project:
  type: book
  output-dir: docs
  resources:
    - images

book:
  title: "STRAT 490R - Understanding AI: From Foundations to Strategy"
  favicon: images/understanding-ai-favicon.png
  author: "Scott Murff"
  date: "5/10/2025"
  chapters:
   - index.qmd
   - 01-machine-learning.qmd
   - 02-llms.qmd

 #  - 03-deep-learning.qmd
   - references.qmd

bibliography: references.bib
csl: informs.csl

format:
  html:
    theme: cosmo
    link-external-icon: true
    link-external-newwindow: true
    css: styles.css
    markdown: default
    
toc-title: On this page
      
number-sections: false



