project:
  type: book
  output-dir: docs
  resources:
    - images

book:
  title: "STRAT 490R - Understanding AI: From Foundations to Strategy"
  author: "Scott Murff"
  date: "5/10/2025"
  chapters:
   - index.qmd
   - 01-history.qmd
   - 02-machine-learning.qmd
   - 03-deep-learning.qmd
#    - summary.qmd
#    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    link-external-icon: true
    link-external-newwindow: true
    css: styles.css
    markdown: default
    
toc-title: On this page
      
number-sections: false



